chore: add .githooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,16 +1,12 @@
 #!/usr/bin/env bash
 
-conventional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"
+echo "Running pre-commit checks..."
 
-commit_message=$(cat "$1")
-
-if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
-   echo -e "\e[32mCommit message meets Conventional Commit standards...\e[0m"
-   exit 0
+./mvnw test-compile -q
+if [ $? -ne 0 ]; then
+    echo "Pre-commit check failed: Code fails to compile!"
+    exit 1
 fi
 
-echo -e "\e[31mThe commit message does not meet the Conventional Commit standard\e[0m"
-echo "An example of a valid message is: "
-echo "  feat(login): add the 'remember me' button"
-echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
-exit 1
+echo "Pre-commit checks passed!"
+exit 0
